### ISSUE TITLE
Add `file://` to StorageRoot entries

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/rDataPipeline#169]

**Comment by richardreeve** [comment]
I think this is important, particularly if it's the same issue that Java had that R is creating a new storage root instead of using the existing storage root that `fair` has made. But I think it's important anyway so that the registry can easily identify the protocol to connect to it.

**Comment by soniamitchell** [comment]
I didn’t know Java had an issue. It’s on the list anyway..

**Comment by richardreeve** [comment]
Ah, yes. I spotted that last week. It was creating a new storage root of `/Users/richardr/.fair/data` because it didn't see that `file:///Users/richardr/.fair/data` was the same one. I think it may be fixed now.

**Comment by soniamitchell** [comment]
Is the datastore now always an absolute path in the config?

**Comment by richardreeve** [comment]
Yes, I'd have thought so. It never occurred to me that it wouldn't be. I suppose we could support a relative path but if so it should be immediately converted to an absolute path before it gets to the registry because otherwise another `fair` call in another directory could never find the data store...

**Comment by soniamitchell** [comment]
Some time ago, prior to there being a single formal data store, it was allowed to be either. Absolute definitely makes more sense though.
